// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using azurelinuxapp.Models;

namespace azurelinuxapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220218053748_initialmigration2")]
    partial class initialmigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("azurelinuxapp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Python",
                            cost = 575.45000000000005,
                            description = "this book covers information about core python and python db"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java",
                            cost = 575.45000000000005,
                            description = "this book covers information about core java and jdbc"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#",
                            cost = 575.45000000000005,
                            description = "this book covers information about core C# and some dotnet technologies"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
